repos:
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--config=pyproject.toml]
-   repo:  https://github.com/csachs/pyproject-flake8
    rev: v6.0.0.post1
    hooks:
    -   id: pyproject-flake8
        entry: pflake8
        args: [--config=pyproject.toml]
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
        files: ".ipynb"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args: [--config-file=pyproject.toml]
        additional_dependencies: [types-requests]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort